<?php
return array(
'Admin'	=>	array(
				'CouponCode'	=>	array(
									'all'			=>	array('action'=>'', 'name'=>'模块管理'),
									'index'			=>	array('action'=>'index', 'name'=>'查看优惠券列表'),
									'best'			=>	array('action'=>'best', 'name'=>'查看每日精选优惠券'),
									'add'			=>	array('action'=>'add', 'name'=>'添加优惠券'),
									'add_code'		=>	array('action'=>'add_code', 'name'=>'添加优惠券代码'),
									'code'			=>	array('action'=>'code', 'name'=>'查看优惠券代码列表'),
									'del'			=>	array('action'=>'del', 'name'=>'删除优惠券'),
									'del_code'		=>	array('action'=>'del_code', 'name'=>'删除优惠券代码'),
									'edit'			=>	array('action'=>'edit', 'name'=>'编辑优惠券'),
									'edit_best'		=>	array('action'=>'edit_best', 'name'=>'编辑精选优惠券'),
									'import'		=>	array('action'=>'import', 'name'=>'批量导入优惠券'),
									'set_best'		=>	array('action'=>'set_best', 'name'=>'设置精选优惠券'),
									'unbest'		=>	array('action'=>'unbest', 'name'=>'删除精选优惠券'),
									'view'			=>	array('action'=>'view', 'name'=>'查看优惠券详情'),
									'sort_order'	=>	array('action'=>'sort_order', 'name'=>'修改优惠券排序'),
									'is_active'		=>	array('action'=>'is_active', 'name'=>'激活优惠券'),
									),
				'CouponCodeMall' =>	array(
									'all'			=>	array('action'=>'', 'name'=>'模块管理'),
									'active'		=>	array('action'=>'active', 'name'=>'激活商家'),
									'add'			=>	array('action'=>'add', 'name'=>'添加商家'),
									'del'			=>	array('action'=>'del', 'name'=>'删除商家'),
									'edit'			=>	array('action'=>'edit', 'name'=>'编辑商家'),
									'index'			=>	array('action'=>'index', 'name'=>'查看商家列表'),
									'rec'			=>	array('action'=>'rec', 'name'=>'推荐商家'),
									'recs'			=>	array('action'=>'recs', 'name'=>'查看推荐商家列表'),
									'select'		=>	array('action'=>'select', 'name'=>'选择商家'),
									'unactive'		=>	array('action'=>'unactive', 'name'=>'屏蔽商家'),
									'unrec'			=>	array('action'=>'unrec', 'name'=>'取消商家推荐'),
									'view'			=>	array('action'=>'view', 'name'=>'查看商家详情'),
									'sort_order'	=>	array('action'=>'sort_order', 'name'=>'修改商家排序'),
									'coupon_mall_rec_sort_order'	=>	array('action'=>'coupon_mall_rec_sort_order', 'name'=>'修改推荐商家排序'),
									),
				'MallPromotion' =>	array(
									'all'			=>	array('action'=>'', 'name'=>'模块管理'),
									'add'			=>	array('action'=>'add', 'name'=>'添加'),
									'del'			=>	array('action'=>'del', 'name'=>'删除'),
									'edit'			=>	array('action'=>'edit', 'name'=>'编辑'),
									'index'			=>	array('action'=>'index', 'name'=>'查看列表'),
									'view'			=>	array('action'=>'view', 'name'=>'查看详情'),
									'sort_order'	=>	array('action'=>'sort_order', 'name'=>'修改排序'),
									),
				'MallZhekou' =>	array(
									'all'			=>	array('action'=>'', 'name'=>'模块管理'),
									'add'			=>	array('action'=>'add', 'name'=>'添加'),
									'del'			=>	array('action'=>'del', 'name'=>'删除'),
									'edit'			=>	array('action'=>'edit', 'name'=>'编辑'),
									'index'			=>	array('action'=>'index', 'name'=>'查看列表'),
									'view'			=>	array('action'=>'view', 'name'=>'查看详情'),
									'sort_order'	=>	array('action'=>'sort_order', 'name'=>'修改排序'),
									'add_category'	=>	array('action'=>'add_category', 'name'=>'添加分类'),
									'edit_category'	=>	array('action'=>'edit_category', 'name'=>'编辑分类'),
									'del_category'	=>	array('action'=>'del_category', 'name'=>'删除分类'),
									'category'		=>	array('action'=>'category', 'name'=>'查看分类列表'),
									'zhekou_category_sort_order'	=>	array('action'=>'zhekou_category_sort_order', 'name'=>'修改分类排序'),
									),
				'CouponCodeCategory' =>	array(
									'all'			=>	array('action'=>'', 'name'=>'模块管理'),
									'add'			=>	array('action'=>'add', 'name'=>'添加分类'),
									'del'			=>	array('action'=>'del', 'name'=>'删除分类'),
									'edit'			=>	array('action'=>'edit', 'name'=>'编辑分类'),
									'index'			=>	array('action'=>'index', 'name'=>'查看分类列表'),
									'sort_order'	=>	array('action'=>'sort_order', 'name'=>'修改排序'),
									'coupon_code_category_show_index'	=>	array('action'=>'coupon_code_category_show_index', 'name'=>'设置首页显示')
									),
				'Article' 		=>	array(
									'all'			=>	array('action'=>'', 'name'=>'模块管理'),
									'add'			=>	array('action'=>'add', 'name'=>'添加文章'),
									'add_category'	=>	array('action'=>'add_category', 'name'=>'添加分类'),
									'build_html'	=>	array('action'=>'build_html', 'name'=>'生成静态'),
									'category'		=>	array('action'=>'category', 'name'=>'查看分类列表'),
									'del'			=>	array('action'=>'del', 'name'=>'删除文章'),
									'del_category'	=>	array('action'=>'del_category', 'name'=>'删除分类'),
									'edit'			=>	array('action'=>'edit', 'name'=>'编辑文章'),
									'edit_category'	=>	array('action'=>'edit_category', 'name'=>'编辑文章分类'),
									'index'			=>	array('action'=>'index', 'name'=>'查看文章列表'),
									),
				'Adv' 		=>	array(
									'all'			=>	array('action'=>'', 'name'=>'模块管理'),
									'add'			=>	array('action'=>'add', 'name'=>'添加广告'),
									'del'			=>	array('action'=>'del', 'name'=>'删除广告'),
									'edit'			=>	array('action'=>'edit', 'name'=>'编辑广告'),
									'index'			=>	array('action'=>'index', 'name'=>'查看广告列表'),
									),
				'AdvPosition'=>	array(
									'all'			=>	array('action'=>'', 'name'=>'模块管理'),
									'add'			=>	array('action'=>'add', 'name'=>'添加广告位'),
									'del'			=>	array('action'=>'del', 'name'=>'删除广告位'),
									'edit'			=>	array('action'=>'edit', 'name'=>'编辑广告位'),
									'index'			=>	array('action'=>'index', 'name'=>'查看广告位列表'),
									),
				'FriendLink'=>	array(
									'all'			=>	array('action'=>'', 'name'=>'模块管理'),
									'add'			=>	array('action'=>'add', 'name'=>'添加链接'),
									'del'			=>	array('action'=>'del', 'name'=>'删除链接'),
									'edit'			=>	array('action'=>'edit', 'name'=>'编辑链接'),
									'index'			=>	array('action'=>'index', 'name'=>'查看链接列表'),
									),
				'Member'	=>	array(
									'all'			=>	array('action'=>'', 'name'=>'模块管理'),
									'index'			=>	array('action'=>'index', 'name'=>'查看会员列表'),
									'User_is_locked'=>	array('action'=>'User_is_locked', 'name'=>'锁定'),
									),
				'Payment'	=>	array(
									'all'			=>	array('action'=>'', 'name'=>'模块管理'),
									'index'			=>	array('action'=>'index', 'name'=>'查看充值记录列表'),
									'del'			=>	array('action'=>'del', 'name'=>'删除充值记录'),
									'send_goods'	=>	array('action'=>'send_goods', 'name'=>'发货'),
									'finish'		=>	array('action'=>'finish', 'name'=>'确认完成'),
									),
			),
);